export const SET_REQUIREMENT_VIEW_TYPE="SET_REQUIREMENT_VIEW_TYPE";

export const GET_REQUIREMENT_RECORD_REQUEST="GET_REQUIREMENT_RECORD_REQUEST";
export const GET_REQUIREMENT_RECORD_SUCCESS="GET_REQUIREMENT_RECORD_SUCCESS";
export const GET_REQUIREMENT_RECORD_FAILURE="GET_REQUIREMENT_RECORD_FAILURE";


export const EMPTY_REQUIREMENT_TABLE = "EMPTY_REQUIREMENT_TABLE";

export const GET_ALL_REQUIREMENT_TABLE_REQUEST =
  "GET_ALL_REQUIREMENT_TABLE_REQUEST";
export const GET_ALL_REQUIREMENT_TABLE_SUCCESS=
  "GET_ALL_REQUIREMENT_TABLE_SUCCESS";
export const GET_ALL_REQUIREMENT_TABLE_FAILURE =
  "GET_ALL_REQUIREMENT_TABLE_FAILURE";

  export const INPUT_JOB_ORDER_SEARCH_DATA_REQUEST="INPUT_JOB_ORDER_SEARCH_DATA_REQUEST";
export const INPUT_JOB_ORDER_SEARCH_DATA_SUCCESS="INPUT_JOB_ORDER_SEARCH_DATA_SUCCESS";
export const INPUT_JOB_ORDER_SEARCH_DATA_FAILURE="INPUT_JOB_ORDER_SEARCH_DATA_FAILURE";
