export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";



export const ADD_ROLES_REQUEST = "ADD_ROLES_REQUEST";
export const ADD_ROLES_SUCCESS = "ADD_ROLES_SUCCESS";
export const ADD_ROLES_FAILURE = "ADD_ROLES_FAILURE";


export const UPDATE_ROLES_REQUEST = "UPDATE_ROLES_REQUEST";
export const UPDATE_ROLES_SUCCESS = "UPDATE_ROLES_SUCCESS";
export const UPDATE_ROLES_FAILURE = "UPDATE_ROLES_FAILURE";


export const REMOVE_ROLES_REQUEST = "REMOVE_ROLES_REQUEST";
export const REMOVE_ROLES_SUCCESS = "REMOVE_ROLES_SUCCESS";
export const REMOVE_ROLES_FAILURE = "REMOVE_ROLES_FAILURE";


export const GET_TALENT_ROLES_REQUEST = "GET_TALENT_ROLES_REQUEST";
export const GET_TALENT_ROLES_SUCCESS = "GET_TALENT_ROLES_SUCCESS";
export const GET_TALENT_ROLES_FAILURE = "GET_TALENT_ROLES_FAILURE";

export const ADD_TALENT_ROLES_REQUEST = "ADD_TALENT_ROLES_REQUEST";
export const ADD_TALENT_ROLES_SUCCESS = "ADD_TALENT_ROLES_SUCCESS";
export const ADD_TALENT_ROLES_FAILURE = "ADD_TALENT_ROLES_FAILURE";


