export const GET_DOCUMENTS_REQUEST = "GET_DOCUMENTS_REQUEST";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const GET_DOCUMENTS_FAILURE = "GET_DOCUMENTS_FAILURE";

export const ADD_DOCUMENTS_REQUEST = "ADD_DOCUMENTS_REQUEST";
export const ADD_DOCUMENTS_SUCCESS = "ADD_DOCUMENTS_SUCCESS";
export const ADD_DOCUMENTS_FAILURE = "ADD_DOCUMENTS_FAILURE";

export const REMOVE_DOCUMENTS_REQUEST = "REMOVE_DOCUMENTS_REQUEST";
export const REMOVE_DOCUMENTS_SUCCESS = "REMOVE_DOCUMENTS_SUCCESS";
export const REMOVE_DOCUMENTS_FAILURE = "REMOVE_DOCUMENTS_FAILURE";

export const UPDATE_DOCUMENTS_REQUEST = "UPDATE_DOCUMENTS_REQUEST";
export const UPDATE_DOCUMENTS_SUCCESS = "UPDATE_DOCUMENTS_SUCCESS";
export const UPDATE_DOCUMENTS_FAILURE = "UPDATE_DOCUMENTS_FAILURE";

