export const GET_SKILLS_CLOUD_REQUEST = "GET_SKILLS_CLOUD_REQUEST";
export const GET_SKILLS_CLOUD_SUCCESS = "GET_SKILLS_CLOUD_SUCCESS";
export const GET_SKILLS_CLOUD_FAILURE = "GET_SKILLS_CLOUD_FAILURE";

export const CHANGE_SELECTED_TIME_INTERVAL_REPORT =
  "CHANGE_SELECTED_TIME_INTERVAL_REPORT";
export const SET_TIME_INTERVAL_REPORT = "SET_TIME_INTERVAL_REPORT";

export const GET_ORDER_LIST_BY_ORDER_ID_REQUEST="GET_ORDER_LIST_BY_ORDER_ID_REQUEST";
export const GET_ORDER_LIST_BY_ORDER_ID_SUCCESS="GET_ORDER_LIST_BY_ORDER_ID_SUCCESS";
export const GET_ORDER_LIST_BY_ORDER_ID_FAILURE="GET_ORDER_LIST_BY_ORDER_ID_FAILURE";

export const SET_DASHBOARD_VIEW_TYPE="SET_DASHBOARD_VIEW_TYPE";

export const GET_DATE_WISE_REPORT_REQUEST = "GET_DATE_WISE_REPORT_REQUEST";
export const GET_DATE_WISE_REPORT_SUCCESS = "GET_DATE_WISE_REPORT_SUCCESS";
export const GET_DATE_WISE_REPORT_FAILURE = "GET_DATE_WISE_REPORT_FAILURE";

export const SET_SELECTED_REPORT_TYPE = "SET_SELECTED_REPORT_TYPE";

export const SET_SUB_SELECTED_REPORT_TYPE = "SET_SUB_SELECTED_REPORT_TYPE";


export const GET_DASHBOARD_TABLE_REQUEST = "GET_DASHBOARD_TABLE_REQUEST";
export const GET_DASHBOARD_TABLE_SUCCESS = "GET_DASHBOARD_TABLE_SUCCESS";
export const GET_DASHBOARD_TABLE_FAILURE = "GET_DASHBOARD_TABLE_FAILURE";

export const GET_RECRUITER_DASHBOARD_LIST_REQUEST = "GET_RECRUITER_DASHBOARD_LIST_REQUEST";
export const GET_RECRUITER_DASHBOARD_LIST_SUCCESS = "GET_RECRUITER_DASHBOARD_LIST_SUCCESS";
export const GET_RECRUITER_DASHBOARD_LIST_FAILURE = "GET_RECRUITER_DASHBOARD_LIST_FAILURE";

export const GET_DASHBOARD_TABLE_PROGRESS_REQUEST = "GET_DASHBOARD_TABLE_PROGRESS_REQUEST";
export const GET_DASHBOARD_TABLE_PROGRESS_SUCCESS = "GET_DASHBOARD_TABLE_PROGRESS_SUCCESS";
export const GET_DASHBOARD_TABLE_PROGRESS_FAILURE = "GET_DASHBOARD_TABLE_PROGRESS_FAILURE";

export const GET_DASHBOARD_COMMISSION_TABLE_REQUEST = "GET_DASHBOARD_COMMISSION_TABLE_REQUEST";
export const GET_DASHBOARD_COMMISSION_TABLE_SUCCESS = "GET_DASHBOARD_COMMISSION_TABLE_SUCCESS";
export const GET_DASHBOARD_COMMISSION_TABLE_FAILURE = "GET_DASHBOARD_COMMISSION_TABLE_FAILURE";

export const GET_DASHBOARD_CUSTOMER_CHART_REQUEST = "GET_DASHBOARD_CUSTOMER_CHART_REQUEST";
export const GET_DASHBOARD_CUSTOMER_CHART_SUCCESS = "GET_DASHBOARD_CUSTOMER_CHART_SUCCESS";
export const GET_DASHBOARD_CUSTOMER_CHART_FAILURE = "GET_DASHBOARD_CUSTOMER_CHART_FAILURE";