export const SET_EMPLOYEE_VIEW_TYPE = "SET_EMPLOYEE_VIEW_TYPE";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

export const GET_EMPLOYEE_LIST_REQUEST = "GET_EMPLOYEE_LIST_REQUEST";
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS";
export const GET_EMPLOYEE_LIST_FAILURE = "GET_EMPLOYEE_LIST_FAILURE";

export const GET_EMPLOYEE_BY_ID_REQUEST = "GET_EMPLOYEE_BY_ID_REQUEST";
export const GET_EMPLOYEE_BY_ID_SUCCESS = "GET_EMPLOYEE_BY_ID_SUCCESS";
export const GET_EMPLOYEE_BY_ID_FAILURE = "GET_EMPLOYEE_BY_ID_FAILURE";

export const UPDATE_EMPLOYEE_BY_ID_REQUEST = "UPDATE_EMPLOYEE_BY_ID_REQUEST";
export const UPDATE_EMPLOYEE_BY_ID_SUCCESS = "UPDATE_EMPLOYEE_BY_ID_SUCCESS";
export const UPDATE_EMPLOYEE_BY_ID_FAILURE = "UPDATE_EMPLOYEE_BY_ID_FAILURE";

export const HANDLE_EMPLOYEE_MODAL = "HANDLE_EMPLOYEE_MODAL";
export const SET_CLEARBIT_DATA = "SET_CLEARBIT_DATA";

export const UPDATE_EMPLOYEE_ADDRESS = "UPDATE_EMPLOYEE_ADDRESS";
export const ADD_EMPLOYEE_ADDRESS = "ADD_EMPLOYEE_ADDRESS";

/**
  Employees notes
 */

export const GET_NOTES_LIST_BY_EMPLOYEE_ID_REQUEST =
  "GET_NOTES_LIST_BY_EMPLOYEE_ID_REQUEST";
export const GET_NOTES_LIST_BY_EMPLOYEE_ID_SUCCESS =
  "GET_NOTES_LIST_BY_EMPLOYEE_ID_SUCCESS";
export const GET_NOTES_LIST_BY_EMPLOYEE_ID_FAILURE =
  "GET_NOTES_LIST_BY_EMPLOYEE_ID_FAILURE";

//Employees notes

//employees document

export const GET_EMPLOYEE_DOCUMENTS_REQUEST = "GET_EMPLOYEE_DOCUMENTS_REQUEST";
export const GET_EMPLOYEE_DOCUMENTS_SUCCESS = "GET_EMPLOYEE_DOCUMENTS_SUCCESS";
export const GET_EMPLOYEE_DOCUMENTS_FAILURE = "GET_EMPLOYEE_DOCUMENTS_FAILURE";

export const DELETE_DOCUMENT_REQUEST = "DELETE_DOCUMENT_REQUEST";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_FAILURE = "DELETE_DOCUMENT_FAILURE";

export const HANDLE_DOCUMENT_UPLOAD_MODAL = "HANDLE_DOCUMENT_UPLOAD_MODAL";

export const ADD_EMPLOYEE_DOCUMENT_REQUEST = "ADD_EMPLOYEE_DOCUMENT_REQUEST";
export const ADD_EMPLOYEE_DOCUMENT_SUCCESS = "ADD_EMPLOYEE_DOCUMENT_SUCCESS";
export const ADD_EMPLOYEE_DOCUMENT_FAILURE = "ADD_EMPLOYEE_DOCUMENT_FAILURE";

export const HANDLE_EMPLOYEE_DRAWER_FOR_ADMIN =
  "HANDLE_EMPLOYEE_DRAWER_FOR_ADMIN";

//suspend
export const SUSPEND_EMPLOYEE_REQUEST = "SUSPEND_EMPLOYEE_REQUEST";
export const SUSPEND_EMPLOYEE_SUCCESS = "SUSPEND_EMPLOYEE_SUCCESS";
export const SUSPEND_EMPLOYEE_FAILURE = "SUSPEND_EMPLOYEE_FAILURE";

//search
export const INPUT_EMPLOYEE_SEARCH_DATA_REQUEST =
  "INPUT_EMPLOYEE_SEARCH_DATA_REQUEST";
export const INPUT_EMPLOYEE_SEARCH_DATA_SUCCESS =
  "INPUT_EMPLOYEE_SEARCH_DATA_SUCCESS";
export const INPUT_EMPLOYEE_SEARCH_DATA_FAILURE =
  "INPUT_EMPLOYEE_SEARCH_DATA_FAILURE";

  export const ADD_SHARE_EMPLOYEE_PERMISSION_REQUEST=
  "ADD_SHARE_EMPLOYEE_PERMISSION_REQUEST";
  export const ADD_SHARE_EMPLOYEE_PERMISSION_SUCCESS=
  "ADD_SHARE_EMPLOYEE_PERMISSION_SUCCESS";
  export const ADD_SHARE_EMPLOYEE_PERMISSION_FAILURE=
  "ADD_SHARE_EMPLOYEE_PERMISSION_FAILURE";

export const GET_PERMISSIONS_LIST_REQUEST = "GET_PERMISSIONS_LIST_REQUEST";
export const GET_PERMISSIONS_LIST_SUCCESS = "GET_PERMISSIONS_LIST_SUCCESS";
export const GET_PERMISSIONS_LIST_FAILURE = "GET_PERMISSIONS_LIST_FAILURE";


export const SUSPEND_STATUS_REQUEST = "SUSPEND_STATUS_REQUEST";
export const SUSPEND_STATUS_SUCCESS = "SUSPEND_STATUS_SUCCESS";
export const SUSPEND_STATUS_FAILURE = "SUSPEND_STATUS_FAILURE";

export const EMPLOYEE_STATUS_REQUEST = "EMPLOYEE_STATUS_REQUEST";
export const EMPLOYEE_STATUS_SUCCESS = "EMPLOYEE_STATUS_SUCCESS";
export const EMPLOYEE_STATUS_FAILURE = "EMPLOYEE_STATUS_FAILURE";

